[PM-13] Add new exercises
power-meter/android-client pull request #29
Opened 2019-12-09 03:58 UTC by brian-norman

Decided to go with full dialog as per the [Material Design Guidelines](https://material.io/components/dialogs/#full-screen-dialog). I'm also not doing error checking for input yet, so it'll crash if you don't enter valid data! Felt like a good PR to get out regardless to unblock the squad 😄

2019-12-09 04:00 UTC, brian-norman commented on app/src/main/java/io/mochahub/powermeter/models/Exercise.kt
> +    val personalRecord: Double,
We used Double in the Room Entity but didn't match it here!

2019-12-11 03:57 UTC, zahin-mohammad requested changes
[Bug] New exercise gets duped in UI.
- Create a new exercise
- Navigate to another page via navbar
- Navigate to exercises page
- Observe dupe

2019-12-11 03:57 UTC, zahin-mohammad commented on app/src/main/res/menu/menu_new_exercise.xml
> +            android:title="SAVE"
Can we make this a string resource?

2019-12-11 03:57 UTC, zahin-mohammad commented on app/src/main/res/layout/dialog_new_exercise.xml
> +            android:hint="Muscle Group"
Can we make this a string resource?

2019-12-11 03:57 UTC, zahin-mohammad commented on app/src/main/res/layout/dialog_new_exercise.xml
> +            android:hint="Personal Record"
Can we make this a string resource?

2019-12-11 03:57 UTC, zahin-mohammad commented on app/src/main/res/layout/dialog_new_exercise.xml
> +            android:hint="Name"
Can we make this a string resource?

2019-12-11 03:57 UTC, zahin-mohammad commented on app/src/main/java/io/mochahub/powermeter/exercises/NewExerciseDialog.kt
> +        // TODO: The toolbar's X icon isn't final, need to figure out how to make it custom to night mode
Don't think it needs to be custom to night mode. It should always stay white I think, like the toolbar title.

2019-12-11 03:57 UTC, zahin-mohammad commented on app/src/main/res/drawable/ic_close_black_24dp.xml
> +</vector>
Let's make this white and rename to `ic_close_white_24dp.xml`

2019-12-11 06:33 UTC, brian-norman commented
@zahin-mohammad nice catch with the bug! Thanks 💯

2019-12-11 22:58 UTC, zahin-mohammad commented
[PM-32] (for tracking)

2019-12-13 05:02 UTC, zahin-mohammad requested changes
I added some code suggestions.

2019-12-13 05:02 UTC, zahin-mohammad commented on app/src/main/res/layout/dialog_new_exercise.xml
> +            android:padding="16dp"
Padding will cause the hint and the textbox outline to overlap when typing. Margin will give the expected result.
```suggestion
            android:layout_margin="16dp"
```

2019-12-13 05:02 UTC, zahin-mohammad commented on app/src/main/res/layout/dialog_new_exercise.xml
> +            android:padding="16dp"
Padding will cause the hint and the textbox outline to overlap. Margin will give the expected result.
```suggestion
            android:layout_margin="16dp"
```

2019-12-13 05:02 UTC, zahin-mohammad commented on app/src/main/res/layout/dialog_new_exercise.xml
> +            android:padding="16dp"
Padding will cause the hint and the textbox outline to overlap. Margin will give the expected result.
```suggestion
            android:layout_margin="16dp"
```

2019-12-13 05:02 UTC, zahin-mohammad commented on app/src/main/res/layout/dialog_new_exercise.xml
> +                android:id="@+id/newExercisePRText"
```suggestion
                android:id="@+id/newExercisePRText"
                android:inputType="numberDecimal"
```

2019-12-13 06:15 UTC, zahin-mohammad approved these changes

2019-12-13 06:16 UTC, merged